import type { CatalogModelDefinition, CatalogProviderId } from "./types.ts";

export interface SnapshotProviderData {
  models: Record<string, CatalogModelDefinition>;
}

export const MODEL_CATALOG_SNAPSHOT: Record<CatalogProviderId, SnapshotProviderData> = {
  anthropic: {
    models: {
      "claude-fable-5": {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        releaseDate: "2026-06-07",
        lastUpdated: "2026-06-09",
        reasoning: true,
        toolCall: true,
      },
      "claude-haiku-4-5": {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5 (latest)",
        releaseDate: "2025-10-15",
        lastUpdated: "2025-10-15",
        reasoning: true,
        toolCall: true,
      },
      "claude-haiku-4-5-20251001": {
        id: "claude-haiku-4-5-20251001",
        name: "Claude Haiku 4.5",
        releaseDate: "2025-10-15",
        lastUpdated: "2025-10-15",
        reasoning: true,
        toolCall: true,
      },
      "claude-opus-4-5": {
        id: "claude-opus-4-5",
        name: "Claude Opus 4.5 (latest)",
        releaseDate: "2025-11-24",
        lastUpdated: "2025-11-24",
        reasoning: true,
        toolCall: true,
      },
      "claude-opus-4-5-20251101": {
        id: "claude-opus-4-5-20251101",
        name: "Claude Opus 4.5",
        releaseDate: "2025-11-24",
        lastUpdated: "2025-11-01",
        reasoning: true,
        toolCall: true,
      },
      "claude-opus-4-6": {
        id: "claude-opus-4-6",
        name: "Claude Opus 4.6",
        releaseDate: "2026-02-04",
        lastUpdated: "2026-03-13",
        reasoning: true,
        toolCall: true,
      },
      "claude-opus-4-7": {
        id: "claude-opus-4-7",
        name: "Claude Opus 4.7",
        releaseDate: "2026-04-14",
        lastUpdated: "2026-04-16",
        reasoning: true,
        toolCall: true,
      },
      "claude-opus-4-8": {
        id: "claude-opus-4-8",
        name: "Claude Opus 4.8",
        releaseDate: "2026-05-28",
        lastUpdated: "2026-05-28",
        reasoning: true,
        toolCall: true,
      },
      "claude-opus-5": {
        id: "claude-opus-5",
        name: "Claude Opus 5",
        releaseDate: "2026-07-24",
        lastUpdated: "2026-07-24",
        reasoning: true,
        toolCall: true,
      },
      "claude-sonnet-4-5": {
        id: "claude-sonnet-4-5",
        name: "Claude Sonnet 4.5 (latest)",
        releaseDate: "2025-09-29",
        lastUpdated: "2025-09-29",
        reasoning: true,
        toolCall: true,
      },
      "claude-sonnet-4-5-20250929": {
        id: "claude-sonnet-4-5-20250929",
        name: "Claude Sonnet 4.5",
        releaseDate: "2025-09-29",
        lastUpdated: "2025-09-29",
        reasoning: true,
        toolCall: true,
      },
      "claude-sonnet-4-6": {
        id: "claude-sonnet-4-6",
        name: "Claude Sonnet 4.6",
        releaseDate: "2026-02-17",
        lastUpdated: "2026-03-13",
        reasoning: true,
        toolCall: true,
      },
      "claude-sonnet-5": {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        releaseDate: "2026-06-29",
        lastUpdated: "2026-06-30",
        reasoning: true,
        toolCall: true,
      },
    },
  },
  openai: {
    models: {
      "chatgpt-image-latest": {
        id: "chatgpt-image-latest",
        name: "chatgpt-image-latest",
        releaseDate: "2025-12-16",
        lastUpdated: "2025-12-16",
        reasoning: false,
        toolCall: false,
      },
      "gpt-3.5-turbo": {
        id: "gpt-3.5-turbo",
        name: "GPT-3.5-turbo",
        status: "deprecated",
        releaseDate: "2023-03-01",
        lastUpdated: "2023-11-06",
        reasoning: false,
        toolCall: false,
      },
      "gpt-4": {
        id: "gpt-4",
        name: "GPT-4",
        status: "deprecated",
        releaseDate: "2023-11-06",
        lastUpdated: "2024-04-09",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4-turbo": {
        id: "gpt-4-turbo",
        name: "GPT-4 Turbo",
        status: "deprecated",
        releaseDate: "2023-11-06",
        lastUpdated: "2024-04-09",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4.1": {
        id: "gpt-4.1",
        name: "GPT-4.1",
        releaseDate: "2025-04-14",
        lastUpdated: "2025-04-14",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4.1-mini": {
        id: "gpt-4.1-mini",
        name: "GPT-4.1 mini",
        releaseDate: "2025-04-14",
        lastUpdated: "2025-04-14",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4.1-nano": {
        id: "gpt-4.1-nano",
        name: "GPT-4.1 nano",
        status: "deprecated",
        releaseDate: "2025-04-14",
        lastUpdated: "2025-04-14",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4o": {
        id: "gpt-4o",
        name: "GPT-4o",
        releaseDate: "2024-05-13",
        lastUpdated: "2024-08-06",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4o-2024-05-13": {
        id: "gpt-4o-2024-05-13",
        name: "GPT-4o (2024-05-13)",
        status: "deprecated",
        releaseDate: "2024-05-13",
        lastUpdated: "2024-05-13",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4o-2024-08-06": {
        id: "gpt-4o-2024-08-06",
        name: "GPT-4o (2024-08-06)",
        releaseDate: "2024-08-06",
        lastUpdated: "2024-08-06",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4o-2024-11-20": {
        id: "gpt-4o-2024-11-20",
        name: "GPT-4o (2024-11-20)",
        releaseDate: "2024-11-20",
        lastUpdated: "2024-11-20",
        reasoning: false,
        toolCall: true,
      },
      "gpt-4o-mini": {
        id: "gpt-4o-mini",
        name: "GPT-4o mini",
        releaseDate: "2024-07-18",
        lastUpdated: "2024-07-18",
        reasoning: false,
        toolCall: true,
      },
      "gpt-5": {
        id: "gpt-5",
        name: "GPT-5",
        releaseDate: "2025-08-07",
        lastUpdated: "2025-08-07",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5-mini": {
        id: "gpt-5-mini",
        name: "GPT-5 Mini",
        releaseDate: "2025-08-07",
        lastUpdated: "2025-08-07",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5-nano": {
        id: "gpt-5-nano",
        name: "GPT-5 Nano",
        releaseDate: "2025-08-07",
        lastUpdated: "2025-08-07",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5-pro": {
        id: "gpt-5-pro",
        name: "GPT-5 Pro",
        releaseDate: "2025-10-06",
        lastUpdated: "2025-10-06",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.1": {
        id: "gpt-5.1",
        name: "GPT-5.1",
        releaseDate: "2025-11-13",
        lastUpdated: "2025-11-13",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.2": {
        id: "gpt-5.2",
        name: "GPT-5.2",
        releaseDate: "2025-12-11",
        lastUpdated: "2025-12-11",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.2-chat-latest": {
        id: "gpt-5.2-chat-latest",
        name: "GPT-5.2 Chat",
        releaseDate: "2025-12-11",
        lastUpdated: "2025-12-11",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.2-pro": {
        id: "gpt-5.2-pro",
        name: "GPT-5.2 Pro",
        releaseDate: "2025-12-11",
        lastUpdated: "2025-12-11",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.3-chat-latest": {
        id: "gpt-5.3-chat-latest",
        name: "GPT-5.3 Chat (latest)",
        releaseDate: "2026-03-03",
        lastUpdated: "2026-03-03",
        reasoning: false,
        toolCall: true,
      },
      "gpt-5.3-codex": {
        id: "gpt-5.3-codex",
        name: "GPT-5.3 Codex",
        releaseDate: "2026-02-05",
        lastUpdated: "2026-02-05",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.3-codex-spark": {
        id: "gpt-5.3-codex-spark",
        name: "GPT-5.3 Codex Spark",
        releaseDate: "2026-02-05",
        lastUpdated: "2026-02-05",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.4": {
        id: "gpt-5.4",
        name: "GPT-5.4",
        releaseDate: "2026-03-05",
        lastUpdated: "2026-03-05",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.4-mini": {
        id: "gpt-5.4-mini",
        name: "GPT-5.4 mini",
        releaseDate: "2026-03-17",
        lastUpdated: "2026-03-17",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.4-nano": {
        id: "gpt-5.4-nano",
        name: "GPT-5.4 nano",
        releaseDate: "2026-03-17",
        lastUpdated: "2026-03-17",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.4-pro": {
        id: "gpt-5.4-pro",
        name: "GPT-5.4 Pro",
        releaseDate: "2026-03-05",
        lastUpdated: "2026-03-05",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.5": {
        id: "gpt-5.5",
        name: "GPT-5.5",
        releaseDate: "2026-04-23",
        lastUpdated: "2026-04-23",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.5-pro": {
        id: "gpt-5.5-pro",
        name: "GPT-5.5 Pro",
        releaseDate: "2026-04-23",
        lastUpdated: "2026-04-23",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.6": {
        id: "gpt-5.6",
        name: "GPT-5.6",
        releaseDate: "2026-07-09",
        lastUpdated: "2026-07-09",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.6-luna": {
        id: "gpt-5.6-luna",
        name: "GPT-5.6 Luna",
        releaseDate: "2026-07-09",
        lastUpdated: "2026-07-09",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.6-sol": {
        id: "gpt-5.6-sol",
        name: "GPT-5.6 Sol",
        releaseDate: "2026-07-09",
        lastUpdated: "2026-07-09",
        reasoning: true,
        toolCall: true,
      },
      "gpt-5.6-terra": {
        id: "gpt-5.6-terra",
        name: "GPT-5.6 Terra",
        releaseDate: "2026-07-09",
        lastUpdated: "2026-07-09",
        reasoning: true,
        toolCall: true,
      },
      "gpt-image-1": {
        id: "gpt-image-1",
        name: "gpt-image-1",
        status: "deprecated",
        releaseDate: "2025-04-24",
        lastUpdated: "2025-04-24",
        reasoning: false,
        toolCall: false,
      },
      "gpt-image-1-mini": {
        id: "gpt-image-1-mini",
        name: "gpt-image-1-mini",
        releaseDate: "2025-09-26",
        lastUpdated: "2025-09-26",
        reasoning: false,
        toolCall: false,
      },
      "gpt-image-1.5": {
        id: "gpt-image-1.5",
        name: "gpt-image-1.5",
        releaseDate: "2025-11-25",
        lastUpdated: "2025-11-25",
        reasoning: false,
        toolCall: false,
      },
      "gpt-image-2": {
        id: "gpt-image-2",
        name: "gpt-image-2",
        releaseDate: "2026-04-21",
        lastUpdated: "2026-04-21",
        reasoning: false,
        toolCall: false,
      },
      "gpt-realtime-2.1": {
        id: "gpt-realtime-2.1",
        name: "GPT-Realtime-2.1",
        releaseDate: "2026-07-06",
        lastUpdated: "2026-07-06",
        reasoning: true,
        toolCall: true,
      },
      o1: {
        id: "o1",
        name: "o1",
        status: "deprecated",
        releaseDate: "2024-12-05",
        lastUpdated: "2024-12-05",
        reasoning: true,
        toolCall: true,
      },
      "o1-pro": {
        id: "o1-pro",
        name: "o1-pro",
        status: "deprecated",
        releaseDate: "2025-03-19",
        lastUpdated: "2025-03-19",
        reasoning: true,
        toolCall: true,
      },
      o3: {
        id: "o3",
        name: "o3",
        releaseDate: "2025-04-16",
        lastUpdated: "2025-04-16",
        reasoning: true,
        toolCall: true,
      },
      "o3-mini": {
        id: "o3-mini",
        name: "o3-mini",
        status: "deprecated",
        releaseDate: "2024-12-20",
        lastUpdated: "2025-01-29",
        reasoning: true,
        toolCall: true,
      },
      "o3-pro": {
        id: "o3-pro",
        name: "o3-pro",
        releaseDate: "2025-06-10",
        lastUpdated: "2025-06-10",
        reasoning: true,
        toolCall: true,
      },
      "o4-mini": {
        id: "o4-mini",
        name: "o4-mini",
        status: "deprecated",
        releaseDate: "2025-04-16",
        lastUpdated: "2025-04-16",
        reasoning: true,
        toolCall: true,
      },
      "text-embedding-3-large": {
        id: "text-embedding-3-large",
        name: "text-embedding-3-large",
        releaseDate: "2024-01-25",
        lastUpdated: "2024-01-25",
        reasoning: false,
        toolCall: false,
      },
      "text-embedding-3-small": {
        id: "text-embedding-3-small",
        name: "text-embedding-3-small",
        releaseDate: "2024-01-25",
        lastUpdated: "2024-01-25",
        reasoning: false,
        toolCall: false,
      },
      "text-embedding-ada-002": {
        id: "text-embedding-ada-002",
        name: "text-embedding-ada-002",
        releaseDate: "2022-12-15",
        lastUpdated: "2022-12-15",
        reasoning: false,
        toolCall: false,
      },
    },
  },
  google: {
    models: {
      "deep-research-max-preview-04-2026": {
        id: "deep-research-max-preview-04-2026",
        name: "Deep Research Max Preview (Apr-21-2026)",
        releaseDate: "2026-04-21",
        lastUpdated: "2026-04-21",
        reasoning: true,
        toolCall: true,
      },
      "deep-research-preview-04-2026": {
        id: "deep-research-preview-04-2026",
        name: "Deep Research Preview (Apr-21-2026)",
        releaseDate: "2026-04-21",
        lastUpdated: "2026-04-21",
        reasoning: true,
        toolCall: true,
      },
      "gemini-2.5-computer-use-preview-10-2025": {
        id: "gemini-2.5-computer-use-preview-10-2025",
        name: "Gemini 2.5 Computer Use Preview 10-2025",
        releaseDate: "2025-10-07",
        lastUpdated: "2025-10-07",
        reasoning: true,
        toolCall: true,
      },
      "gemini-2.5-flash": {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        releaseDate: "2025-06-17",
        lastUpdated: "2025-06-17",
        reasoning: true,
        toolCall: true,
      },
      "gemini-2.5-flash-image": {
        id: "gemini-2.5-flash-image",
        name: "Nano Banana",
        releaseDate: "2025-08-26",
        lastUpdated: "2025-08-26",
        reasoning: true,
        toolCall: false,
      },
      "gemini-2.5-flash-lite": {
        id: "gemini-2.5-flash-lite",
        name: "Gemini 2.5 Flash-Lite",
        releaseDate: "2025-06-17",
        lastUpdated: "2025-06-17",
        reasoning: true,
        toolCall: true,
      },
      "gemini-2.5-flash-preview-tts": {
        id: "gemini-2.5-flash-preview-tts",
        name: "Gemini 2.5 Flash Preview TTS",
        releaseDate: "2025-05-01",
        lastUpdated: "2025-05-01",
        reasoning: false,
        toolCall: false,
      },
      "gemini-2.5-pro": {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        releaseDate: "2025-06-17",
        lastUpdated: "2025-06-17",
        reasoning: true,
        toolCall: true,
      },
      "gemini-2.5-pro-preview-tts": {
        id: "gemini-2.5-pro-preview-tts",
        name: "Gemini 2.5 Pro Preview TTS",
        releaseDate: "2025-05-01",
        lastUpdated: "2025-05-01",
        reasoning: false,
        toolCall: false,
      },
      "gemini-3-flash-preview": {
        id: "gemini-3-flash-preview",
        name: "Gemini 3 Flash Preview",
        releaseDate: "2025-12-17",
        lastUpdated: "2025-12-17",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3-pro-image": {
        id: "gemini-3-pro-image",
        name: "Nano Banana Pro",
        releaseDate: "2026-05-28",
        lastUpdated: "2026-05-28",
        reasoning: true,
        toolCall: false,
      },
      "gemini-3-pro-image-preview": {
        id: "gemini-3-pro-image-preview",
        name: "Nano Banana Pro",
        releaseDate: "2025-11-20",
        lastUpdated: "2025-11-20",
        reasoning: true,
        toolCall: false,
      },
      "gemini-3.1-flash-image": {
        id: "gemini-3.1-flash-image",
        name: "Nano Banana 2",
        releaseDate: "2026-05-28",
        lastUpdated: "2026-05-28",
        reasoning: true,
        toolCall: false,
      },
      "gemini-3.1-flash-image-preview": {
        id: "gemini-3.1-flash-image-preview",
        name: "Nano Banana 2",
        releaseDate: "2026-02-26",
        lastUpdated: "2026-02-26",
        reasoning: true,
        toolCall: false,
      },
      "gemini-3.1-flash-lite": {
        id: "gemini-3.1-flash-lite",
        name: "Gemini 3.1 Flash Lite",
        releaseDate: "2026-05-07",
        lastUpdated: "2026-05-07",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.1-flash-lite-image": {
        id: "gemini-3.1-flash-lite-image",
        name: "Nano Banana 2 Lite",
        releaseDate: "2026-06-30",
        lastUpdated: "2026-06-30",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.1-flash-lite-preview": {
        id: "gemini-3.1-flash-lite-preview",
        name: "Gemini 3.1 Flash Lite Preview",
        status: "deprecated",
        releaseDate: "2026-03-03",
        lastUpdated: "2026-03-03",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.1-flash-live-preview": {
        id: "gemini-3.1-flash-live-preview",
        name: "Gemini 3.1 Flash Live Preview",
        releaseDate: "2026-03-26",
        lastUpdated: "2026-03-26",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.1-flash-tts-preview": {
        id: "gemini-3.1-flash-tts-preview",
        name: "Gemini 3.1 Flash TTS Preview",
        releaseDate: "2026-04-15",
        lastUpdated: "2026-04-15",
        reasoning: true,
        toolCall: false,
      },
      "gemini-3.1-pro-preview": {
        id: "gemini-3.1-pro-preview",
        name: "Gemini 3.1 Pro Preview",
        releaseDate: "2026-02-19",
        lastUpdated: "2026-02-19",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.1-pro-preview-customtools": {
        id: "gemini-3.1-pro-preview-customtools",
        name: "Gemini 3.1 Pro Preview Custom Tools",
        releaseDate: "2026-02-19",
        lastUpdated: "2026-02-19",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.5-flash": {
        id: "gemini-3.5-flash",
        name: "Gemini 3.5 Flash",
        releaseDate: "2026-05-19",
        lastUpdated: "2026-05-19",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.5-flash-lite": {
        id: "gemini-3.5-flash-lite",
        name: "Gemini 3.5 Flash Lite",
        releaseDate: "2026-07-21",
        lastUpdated: "2026-07-21",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.5-live-translate-preview": {
        id: "gemini-3.5-live-translate-preview",
        name: "Gemini 3.5 Live Translate Preview",
        releaseDate: "2026-06-09",
        lastUpdated: "2026-06-09",
        reasoning: false,
        toolCall: false,
      },
      "gemini-3.6-flash": {
        id: "gemini-3.6-flash",
        name: "Gemini 3.6 Flash",
        releaseDate: "2026-07-21",
        lastUpdated: "2026-07-21",
        reasoning: true,
        toolCall: true,
      },
      "gemini-3.7-flash": {
        id: "gemini-3.7-flash",
        name: "Gemini 3.7 Flash",
        releaseDate: "2026-08-13",
        lastUpdated: "2026-08-13",
        reasoning: true,
        toolCall: true,
      },
      "gemini-embedding-001": {
        id: "gemini-embedding-001",
        name: "Gemini Embedding 001",
        releaseDate: "2025-05-20",
        lastUpdated: "2025-05-20",
        reasoning: false,
        toolCall: false,
      },
      "gemini-embedding-2": {
        id: "gemini-embedding-2",
        name: "Gemini Embedding 2",
        releaseDate: "2026-04-22",
        lastUpdated: "2026-04-22",
        reasoning: false,
        toolCall: false,
      },
      "gemini-flash-latest": {
        id: "gemini-flash-latest",
        name: "Gemini Flash Latest",
        releaseDate: "2026-05-19",
        lastUpdated: "2026-05-19",
        reasoning: true,
        toolCall: true,
      },
      "gemini-flash-lite-latest": {
        id: "gemini-flash-lite-latest",
        name: "Gemini Flash-Lite Latest",
        releaseDate: "2026-05-07",
        lastUpdated: "2026-05-07",
        reasoning: true,
        toolCall: true,
      },
      "gemini-omni-flash-preview": {
        id: "gemini-omni-flash-preview",
        name: "Gemini Omni Flash Preview",
        releaseDate: "2026-06-30",
        lastUpdated: "2026-06-30",
        reasoning: true,
        toolCall: false,
      },
      "gemini-robotics-er-1.6-preview": {
        id: "gemini-robotics-er-1.6-preview",
        name: "Gemini Robotics-ER 1.6 Preview",
        releaseDate: "2026-04-14",
        lastUpdated: "2026-04-14",
        reasoning: true,
        toolCall: true,
      },
      "gemma-4-26b-a4b-it": {
        id: "gemma-4-26b-a4b-it",
        name: "Gemma 4 26B A4B IT",
        releaseDate: "2026-04-02",
        lastUpdated: "2026-04-02",
        reasoning: true,
        toolCall: true,
      },
      "gemma-4-31b-it": {
        id: "gemma-4-31b-it",
        name: "Gemma 4 31B IT",
        releaseDate: "2026-04-02",
        lastUpdated: "2026-04-02",
        reasoning: true,
        toolCall: true,
      },
      "lyria-3-clip-preview": {
        id: "lyria-3-clip-preview",
        name: "Lyria 3 Clip Preview",
        releaseDate: "2026-03-25",
        lastUpdated: "2026-03-25",
        reasoning: false,
        toolCall: false,
      },
      "lyria-3-pro-preview": {
        id: "lyria-3-pro-preview",
        name: "Lyria 3 Pro Preview",
        releaseDate: "2026-03-25",
        lastUpdated: "2026-03-25",
        reasoning: false,
        toolCall: false,
      },
      "veo-3.1-fast-generate-preview": {
        id: "veo-3.1-fast-generate-preview",
        name: "Veo 3.1 fast",
        releaseDate: "2025-10-15",
        lastUpdated: "2026-01-01",
        reasoning: false,
        toolCall: false,
      },
      "veo-3.1-generate-preview": {
        id: "veo-3.1-generate-preview",
        name: "Veo 3.1",
        status: "beta",
        releaseDate: "2025-10-15",
        lastUpdated: "2026-01",
        reasoning: false,
        toolCall: false,
      },
      "veo-3.1-lite-generate-preview": {
        id: "veo-3.1-lite-generate-preview",
        name: "Veo 3.1 lite",
        releaseDate: "2026-03-31",
        lastUpdated: "2026-03-31",
        reasoning: false,
        toolCall: false,
      },
    },
  },
};
